USE master
GO
-- 
ALTER DATABASE AdventureWorks2019 SET SINGLE_USER WITH ROLLBACK IMMEDIATE
GO

USE master
GO

RESTORE DATABASE AdventureWorks2019 FROM DATABASE_SNAPSHOT = 'AdventureWorks2019_SS'
GO

ALTER DATABASE AdventureWorks2019 SET MULTI_USER;
GO


