USE CursoAnalisis_Archivos
GO

CREATE TABLE Archivos
(
	Id UNIQUEIDENTIFIER ROWGUIDCOL NOT NULL PRIMARY KEY,
	Descripcion VARCHAR(100) NOT NULL,
	Archivo VARBINARY(MAX) FILESTREAM,-- TIPO
	Fecha DATETIME DEFAULT GETDATE()
)
GO