

-- ABC01   FDG02
CREATE TABLE Cursos(
	ID CHAR(5),
	DESCRIPCION VARCHAR(100),
	CORREO VARCHAR(100) NOT NULL, --CORREO A INFORMAR
	FECHA_CREACION DATETIME DEFAULT GETDATE()
	CONSTRAINT PK_Cursos PRIMARY KEY (ID),
	CONSTRAINT UX_CursosCorreo UNIQUE(CORREO),
	-- CONSTRAINT FK_ FOREIGN KEY ...	
	CONSTRAINT CHECK_FECHA CHECK (FECHA_CREACION > '20200101' AND FECHA_CREACION < GETDATE())
)

ALTER TABLE Cursos 
ADD CONSTRAINT CHECK_ID CHECK (ID LIKE '[A-C][B-H][T-Z][0-5][6-9]')

INSERT INTO Cursos (ID,DESCRIPCION,CORREO)
VALUES ('BBT06','Curso 1','octavio')


SELECT * FROM Cursos WHERE CORREO '@"^[^@\s]+@[^@\s]+\.[^@\s]+$"'