CREATE TABLE Alumnos
(
	ID INT IDENTITY,
	NOMBRE VARCHAR(MAX)
)

CREATE NONCLUSTERED INDEX IDX_Alumnos1 ON Alumnos
(
	ID
)
WITH (ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS= ON)


CREATE NONCLUSTERED INDEX IDX_Alumnos2 ON Alumnos
(
	ID DESC
)
WITH (ALLOW_PAGE_LOCKS=ON, ALLOW_ROW_LOCKS= ON)





TRUNCATE TABLE Alumnos
DECLARE @CONTADOR INT = 1

WHILE(@CONTADOR < 5000)
BEGIN
	INSERT INTO Alumnos (NOMBRE) VALUES ('Alumno - ' + CONVERT(VARCHAR(MAX),@CONTADOR))
	SET @CONTADOR = @CONTADOR + 1
	-- 200 LINEAS MAS DE CODIGO
END




BEGIN TRAN
UPDATE Alumnos SET NOMBRE = NOMBRE + '.' WHERE ID = 5


ROLLBACK TRAN
COMMIT TRAN
