
BEGIN TRAN ACTUALIZACION

DECLARE @CONTADOR INT = 1

WHILE(@CONTADOR < 5000)
BEGIN
	WAITFOR DELAY '00:00:01' 
	INSERT INTO Alumnos (NOMBRE) VALUES ('Alumno - ' + CONVERT(VARCHAR(MAX),@CONTADOR))
	SET @CONTADOR = @CONTADOR + 1
	-- 200 LINEAS MAS DE CODIGO
	-- UPDATE
END

-- COMMIT TRAN ACTUALIZACION
-- ROLLBACK TRAN ACTUALIZACION

