USE CursoAnalisisClase05
GO
CREATE SEQUENCE dbo.SEQUENCE_Profesor AS INT
MINVALUE 1
NO MAXVALUE
START WITH 1
GO

SELECT Secuencia1 = NEXT VALUE FOR dbo.SEQUENCE_Profesor -- AS Secuencia

DECLARE @Secuencia INT

SELECT @Secuencia = NEXT VALUE FOR dbo.SEQUENCE_Profesor

SELECT @Secuencia


CREATE SEQUENCE dbo.Secuencia01 AS INT
MINVALUE 2
MAXVALUE 20
START WITH 2
INCREMENT BY 2
CYCLE


-- SELECT @@IDENTITY,SCOPE_IDENTITY(), IDENT_CURRENT('Prueba1')